cc_binary(
    name = "lambchops",
    srcs = ["main.cc"],
    deps = [
        "@absl//absl/types:optional",
    ],
)

cc_test(
    name = "lambchops_test",
    srcs = ["main_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
