load(":glsl.bzl", "glsl")

glsl(
    name = "frag",
    src = "frag.frag",
    out = "frag.spv",
    visibility = ["//visibility:public"],
)

glsl(
    name = "vertex",
    src = "vertex.vert",
    out = "vertex.spv",
    visibility = ["//visibility:public"],
)
